version: '3.8'

services:
  dev:
    build: .
    ports:
      - "3000:3000"
    volumes:
      # ローカルのコードをコンテナにマウント
      - .:/app
      # node_modulesはコンテナ内のものを使用（ローカルのnode_modulesで上書きしない）
      - /app/node_modules
      # Next.jsのキャッシュもコンテナ内で管理
      - /app/.next
    environment:
      # ファイル監視のポーリングを有効化（Docker環境で必要）
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
